#!/usr/bin/env python3
"""Render the household's till receipts and put them in the photo manifest.

    python3 generate/gen_household_photos.py
    python3 generate/gen_household_photos.py --check      # changes nothing

The six rows whose only witness is a paper slip are chosen by the ledger, so
they MOVE whenever the ledger is regenerated — a different seed, a wider window,
a changed weight. Everything downstream of them is expensive and silent when it
goes stale: a rendered scan, a manifest entry, a composite that cost real money
to generate, and a library JPEG.

So this step **reconciles rather than accumulates**. It renders exactly the
scans the current spec names, deletes the ones it does not, and rewrites the
manifest's household block between two markers instead of appending to it. Run
it after `gen_household.py` and before `photos/generate.py`, and `--check` in
anger: an orphaned composite is a photograph of a transaction that no longer
exists, and nothing else in the pipeline can see one.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIX = ROOT / "fixtures/mindmymoney"
SOURCES = FIX / "receipt-photo-sources"
MANIFEST = ROOT / "generate/photos/manifests/alex-carter.yaml"
RAW = ROOT / "generate/photos/raw/alex-carter"
LIBRARY = ROOT / "generate/photos/library/alex-carter/receipts"

BEGIN = "# >>> household till receipts (generated by gen_household_photos.py)"
END = "# <<< household till receipts"

# Where a slip gets photographed, and what is next to it. Keyed by shop, because
# where a person puts a receipt down is a fact about the shop they came from.
SETTINGS = {
    "Café Zeitlupe": [
        ("Friedrichshain, Berlin", 52.5105, 13.4610,
         "photographed on a cafe table beside a half-finished milky coffee and a "
         "folded newspaper, morning light through a window, slight angle"),
        ("Friedrichshain, Berlin", 52.5105, 13.4610,
         "photographed on a small outdoor cafe table beside an empty cake plate "
         "and a fork, late afternoon sun throwing a shadow across the paper"),
    ],
    "Marktstand Grünwinkel": [
        ("Kreuzberg, Berlin", 52.4990, 13.4180,
         "photographed on a kitchen worktop beside a cloth shopping bag with "
         "carrots and apples spilling out of it, overhead, bright midday light"),
        ("Kreuzberg, Berlin", 52.4990, 13.4180,
         "photographed crumpled on a kitchen table beside an egg box and a paper "
         "bag of tomatoes, overhead, domestic clutter, flat indoor light"),
    ],
    "Hofladen Havelgrün": [
        ("Werder an der Havel", 52.3780, 12.9340,
         "photographed on a car dashboard with a country road and bare winter "
         "trees blurred through the windscreen, flat overcast light"),
        ("Werder an der Havel", 52.3780, 12.9340,
         "photographed held in one hand over a wooden farm-shop counter, glass "
         "jars and a crate of cherries behind, warm summer light"),
    ],
    "Bar Nachtkarte": [
        ("Kreuzberg, Berlin", 52.5010, 13.4220,
         "photographed on a dark wooden bar top beside a half-empty glass, warm "
         "low lamplight, shallow depth of field"),
        ("Kreuzberg, Berlin", 52.4990, 13.4180,
         "photographed on a hallway table beside a set of keys and a phone, "
         "late at night, one warm overhead light"),
    ],
}


def offset(day: str) -> str:
    """Berlin's UTC offset. Summer time runs late March to late October, and the
    stamp step writes whatever this says verbatim."""
    month = int(day[5:7])
    return "+02:00" if 4 <= month <= 9 else (
        "+01:00" if month in (11, 12, 1, 2) else "+02:00")


def slug(name: str) -> str:
    table = {"ä": "ae", "ö": "oe", "ü": "ue", "ß": "ss", "é": "e", "&": "und"}
    s = "".join(table.get(c, c) for c in name.lower())
    out = "".join(c if c.isalnum() else "-" for c in s)
    return "-".join(part for part in out.split("-") if part)


def wanted(spec: list) -> list[dict]:
    seen: dict[str, int] = {}
    out = []
    for entry in spec:
        day = entry["when"][:10]
        shop = slug(entry["merchant"])
        seen[entry["merchant"]] = seen.get(entry["merchant"], 0) + 1
        place, lat, lon, scene = SETTINGS[entry["merchant"]][
            (seen[entry["merchant"]] - 1) % len(SETTINGS[entry["merchant"]])]
        out.append({
            "day": day, "when": entry["when"], "merchant": entry["merchant"],
            "png": f"{day}-{shop}-beleg.png",
            "stem": f"{day}-receipt-{shop}-01",
            "place": place, "lat": lat, "lon": lon, "scene": scene,
        })
    return out


def block(rows: list[dict]) -> str:
    lines = [
        BEGIN,
        "# " + "=" * 58,
        "# ERA: receipts — the Carter-Okafor HOUSEHOLD's till slips",
        "#",
        "# A handful of rows in the household's year have no evidence online at",
        "# all: a hired card terminal printed a merchant code and nothing else,",
        "# so no order history, no email and no account page can name them. What",
        "# the household has is the paper, photographed where it was put down.",
        "#",
        "# They are the source for *find out for sure* on an unnamed row, and they",
        "# are why a money round looks at the photo library at all — in a narrow",
        "# window around one payment, never as a sweep.",
        "#",
        "# Spread across months on purpose: several slips from one fortnight is a",
        "# person who has just been told to photograph receipts.",
        "#",
        "# ⚠️ REGENERATED WHOLESALE by gen_household_photos.py. Edit that, not",
        "# this — the rows it describes move whenever the ledger does.",
        "# " + "=" * 58,
    ]
    for r in rows:
        lines += [
            f"- file: {r['stem']}",
            "  era: receipts",
            f"  datetime: {r['when']}:00{offset(r['day'])}",
            f'  location: {{ name: "{r["place"]}", lat: {r["lat"]}, lon: {r["lon"]} }}',
            "  camera: iphone-15-pro",
            "  cast: []",
            f'  scene: "COMPOSITE: fixtures/mindmymoney/receipt-photo-sources/'
            f'{r["png"]} {r["scene"]}"',
            "  style: receipt",
        ]
    lines.append(END)
    return "\n".join(lines) + "\n"


def rewrite_manifest(rows: list[dict], check: bool) -> bool:
    text = MANIFEST.read_text()
    new_block = block(rows)
    if BEGIN in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        updated = head + new_block + tail.lstrip("\n")
    else:
        updated = text.rstrip("\n") + "\n\n" + new_block
    if updated == text:
        return False
    if not check:
        MANIFEST.write_text(updated)
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="report drift and change nothing")
    args = ap.parse_args()

    spec_path = FIX / "receipt-spec.json"
    if not spec_path.exists():
        print(f"no {spec_path.relative_to(ROOT)} — run gen_household.py first")
        return 2
    rows = wanted(json.loads(spec_path.read_text()))
    keep = {r["png"] for r in rows}
    stems = {r["stem"] for r in rows}

    # --- render the scans -------------------------------------------------
    if not args.check:
        subprocess.run(
            [sys.executable, "gen_receipts.py", "--spec", str(spec_path),
             "--out", str(SOURCES), "--seed", "42"],
            cwd=ROOT / "generate", check=True,
            stdout=subprocess.DEVNULL)

    # --- prune what the spec no longer names ------------------------------
    # ⛔ The expensive half. An orphaned composite is a photograph of a
    # transaction that does not exist, and nothing downstream can tell.
    stale = []
    for path in sorted(SOURCES.glob("*.png")):
        if path.name not in keep:
            stale.append(path)
    for folder, suffix in ((RAW, ".png"), (LIBRARY, ".jpg")):
        if not folder.exists():
            continue
        for path in sorted(folder.glob(f"*-receipt-*{suffix}")):
            stem = path.stem
            if stem.startswith(tuple(f"{r['day'][:4]}" for r in rows)) and False:
                continue
            if stem in {s for s in stems}:
                continue
            # only ours: a household slip is one of the shops in SETTINGS
            if any(slug(m) in stem for m in SETTINGS):
                stale.append(path)

    changed = rewrite_manifest(rows, args.check)

    if args.check:
        if stale or changed:
            print("the photo half has DRIFTED from the ledger:")
            for path in stale:
                print(f"  orphaned: {path.relative_to(ROOT)}")
            if changed:
                print("  the manifest block no longer matches the spec")
            print("\nrun gen_household_photos.py, then photos/generate.py --only …")
            return 1
        print(f"  {len(rows)} till receipts, scans, manifest entries — in step.")
        return 0

    for path in stale:
        path.unlink()
        print(f"  pruned {path.relative_to(ROOT)}")
    print(f"  {len(rows)} scans rendered, manifest block rewritten")
    print("\nnow generate the composites:")
    print("  cd generate/photos && python3 generate.py "
          f"--manifest manifests/alex-carter.yaml --only {','.join(sorted(stems))}")
    print("  python3 stamp_exif.py --manifest manifests/alex-carter.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
